name: cct_core
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  highlight_text: ^1.8.0
  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  showcaseview: ^3.0.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Networking
  graphql_flutter: ^5.1.2
  connectivity_plus: ^6.0.5

  # Data Handling
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive: ^2.2.3
  dartz: ^0.10.1

  # Utilities
  unorm_dart: ^0.3.0
  uuid: ^4.5.0
  crypto: ^3.0.5
  get_it: ^8.0.0
  url_launcher: ^6.3.0

  # Device Info
  device_info_plus: ^10.1.2

  # Authentication
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.2
  flutter_secure_storage: ^9.2.2

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_remote_config: ^5.1.2

  # Notifications
  onesignal_flutter: ^5.2.5

  # Custom Packages
  cct_config:
    git:
      url: https://github.com/NinhLuong/flutter_clearn_architecture_config.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/appbar_icon/
    - assets/icon/community_icon/
    - assets/icon/notification_icon/